#! /bin/bash

echo "***************** Cleaning original mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh

wclean all applications
wclean all src

echo "***************** Cleaning ADR mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh
sed -i 's/export WM_AD_MODE=.*/export WM_AD_MODE=ADR/' $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-AD/etc/bashrc
. $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADR/etc/bashrc

wclean all applications
wclean all src

echo "***************** Cleaning ADF mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh
sed -i 's/export WM_AD_MODE=.*/export WM_AD_MODE=ADF/' $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-AD/etc/bashrc
. $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADF/etc/bashrc

wclean all applications
wclean all src

. $DAFOAM_ROOT_PATH/loadDAFoam.sh

