#! /bin/bash

#set -e

export WM_QUIET=true

# compile original mode
echo "***************** Compiling original mode **************"
source $DAFOAM_ROOT_PATH/loadDAFoam.sh

cd src && wmake -j && cd -

cd applications/singleRegionSolvers && wmake hisa && cd -

echo "***************** Compiling ADR mode **************"
source $DAFOAM_ROOT_PATH/loadDAFoam.sh
sed -i 's/export WM_AD_MODE=.*/export WM_AD_MODE=ADR/' $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-AD/etc/bashrc
source $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-AD/etc/bashrc

cd src && wmake -j && cd -

#echo "***************** Compiling ADF mode **************"
source $DAFOAM_ROOT_PATH/loadDAFoam.sh
sed -i 's/export WM_AD_MODE=.*/export WM_AD_MODE=ADF/' $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-AD/etc/bashrc
source $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-AD/etc/bashrc

cd src && wmake -j && cd -

# reset the OpenFOAM environment to the original mode
source $DAFOAM_ROOT_PATH/loadDAFoam.sh

echo "*** Build Successful! ***"


