#! /bin/bash

#set -e

# compile original mode
echo "***************** Compiling original mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh

cd src && wmake -j && cd -

cd applications/singleRegionSolvers && wmake hisa && cd -

#echo "***************** Compiling ADR mode **************"
#. $DAFOAM_ROOT_PATH/loadDAFoam.sh
#. $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADR/etc/bashrc

#cd src && wmake -j && cd -

#echo "***************** Compiling ADF mode **************"
#. $DAFOAM_ROOT_PATH/loadDAFoam.sh
#. $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADF/etc/bashrc

#cd src && wmake -j && cd -

# reset the OpenFOAM environment to the original mode
#. $DAFOAM_ROOT_PATH/loadDAFoam.sh

echo "*** Build Successful! ***"


