#! /bin/bash

#set -e

cd airfoil
rm -rf processor*
decomposePar
mpirun -np 2 hisa -parallel 2>&1 | tee log.txt

python verify.py

sed -i 's/AUSMPlusUp/JST/g' system/fvSchemes

rm -rf processor*
decomposePar
mpirun -np 2 hisa -parallel 2>&1 | tee log_jst.txt

python verify_jst.py

sed -i 's/JST/AUSMPlusUp/g' system/fvSchemes


