#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
set -e

cd mesh

# Cartesian mesh (cfMesh) ..........................
# Extract feature edges
runApplication -s Fms surfaceFeatureEdges gmsh/64a004.stl constant/64a004.fms
runApplication FMSToSurface constant/64a004.fms constant/edges.vtk -exportFeatureEdges
# Bounding patches
runApplication surfaceFeatureEdges gmsh/wingBlock.stl constant/wingBlock.ftr
# Cut-cell Cartesian mesh
runApplication cartesianMesh
if [ -z "$FOAM_API" ] && ( [ "$WM_PROJECT_VERSION" == "dev" ] || [ "$WM_PROJECT_VERSION" -ge "12" ] )
then
    runApplication transformPoints rotate="((0 0 1) (0 1 0))"
else
    runApplication rotateMesh "(0 0 1)" "(0 1 0)"
fi

if [ -z "$FOAM_API" ] && ( [ "$WM_PROJECT_VERSION" == "dev" ] || [ "$WM_PROJECT_VERSION" -ge "10" ] )
then
    echo "type internal;" > system/helperPatchType
else
    echo "type patch;" > system/helperPatchType
fi

# Tet and Cartesian meshes
runApplication createPatch -overwrite
runApplication checkMesh -constant

cd ..

# ----------------------------------------------------------------- end-of-file
